# Technology Icons
vuejs: 'fab fa-vuejs text-green-600'
react: 'fab fa-react text-blue-500'
angular: 'fab fa-angular text-red-600'
nodejs: 'fab fa-node-js text-green-700'
python: 'fab fa-python text-blue-600'
java: 'fab fa-java text-red-500'
cpp: 'fas fa-code text-blue-800'
golang: 'fas fa-code text-blue-500'
docker: 'fab fa-docker text-blue-600'
kubernetes: 'fas fa-dharmachakra text-blue-600'
linux: 'fab fa-linux text-gray-800'
llm: 'fas fa-robot text-purple-600'
swift: 'fab fa-swift text-orange-500'
matlab: 'fas fa-square-root-alt text-blue-500'

# Development Areas
machine-learning: 'fas fa-brain text-purple-500'
deep-learning: 'fas fa-network-wired text-indigo-500'
computer-vision: 'fas fa-eye text-blue-500'
natural-language-processing: 'fas fa-language text-green-500'
web-development: 'fas fa-globe text-blue-400'
mobile-development: 'fas fa-mobile-alt text-gray-600'
backend: 'fas fa-server text-gray-700'
frontend: 'fas fa-desktop text-blue-500'
database: 'fas fa-database text-orange-500'
cloud: 'fas fa-cloud text-blue-300'
devops: 'fas fa-tools text-gray-600'
security: 'fas fa-shield-alt text-red-500'
testing: 'fas fa-vial text-green-500'
api: 'fas fa-plug text-gray-600'
microservices: 'fas fa-cubes text-blue-500'
